--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iLVOEWOCK/SimpleWarps
build-by-default: true
branches:
- main
projects:
  SimpleWarps:
    path: ""
    libs:
      - src: jasonw4331/Commando/Commando # Temporary until the original updates
        version: ^3.1.0
        branch: PM5
...
