name: SimpleWarps
main: wock\SimpleWarps\Warps
api: 5.0.0
version: 1.0.0
author: wockgod

permissions:
  simple_warps.set_warp:
    default: op
  simple_warps.delete_warp:
    default: op
  simple_warps.warp:
    default: true
  simple_warps.list_warps:
    default: true
  simple_warps.reload:
    default: op
